language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-33.0.2
    - android-33
    - extra-android-m2repository

script:
 - ./gradlew clean build
